<?php
/**
 * Interface for "after" middlewares in REST API pipeline.
 *
 * After middlewares are executed **after** the main action handler
 * has produced a response. They can modify the response before
 * it is returned to the client.
 *
 * Each middleware receives:
 * - WP_REST_Request $request — the current REST API request
 * - mixed $response — the response generated by previous middleware or action
 * - callable $next — the next middleware in the pipeline
 *
 * The middleware should call `$next($request, $response)` to continue
 * the pipeline, or return a modified response directly.
 *
 * Example:
 * ```php
 * class AddHeaderMiddleware implements AfterMiddlewareInterface {
 *
 *      public function handle(WP_REST_Request $request, mixed $response, callable $next): mixed
 *      {
 *          $response = $next($request, $response);
 *          // Modify response before returning
 *          $response['custom_header'] = 'value';
 *          return $response;
 *      }
 * }
 * ```
 *
 * @package GiApiRoute\Contracts
 * @author Artem <gammaironak@gmail.com>
 * @date 26.11.2025
 */

namespace GiApiRoute\Contracts;

use WP_REST_Request;

interface AfterMiddlewareInterface
{

    /**
     * Handles the response after the main REST action.
     *
     * @param WP_REST_Request $request The current request object
     * @param mixed $response The response generated by previous middleware or action
     * @param callable $next The next middleware in the pipeline
     * @return mixed The final (possibly modified) response
     */
    public function handle(WP_REST_Request $request, mixed $response, callable $next): mixed;

}
